# Generated by Django 4.2.26 on 2025-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankey_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='yo_mama',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
    ]
