# Generated by Django 4.2.26 on 2025-12-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankey_account', '0002_transaction_yo_mama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='yo_mama',
        ),
    ]
