# Generated by Django 4.2.26 on 2025-12-08 16:04

import bankey_account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankey_account', '0003_remove_transaction_yo_mama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=bankey_account.utils.generate_expiration_date),
        ),
    ]
