# Generated by Django 4.2.26 on 2025-12-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankey_account', '0004_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.IntegerField(choices=[(0, 'Debit'), (1, 'Credit')]),
        ),
    ]
