# Generated by Django 4.2.26 on 2025-12-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankey_account', '0005_alter_card_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankey_account.card'),
        ),
    ]
